### ISSUE TITLE
Issues take a long time to load from the notifications screen

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#124]
The transition isn't super smooth. It could just be my slow internet, but it would be nice for the issue screen with the loading indicator to appear immediately after clicking on the issue.

**Comment by housseindjirdeh** [comment]
Yep this is definitely something we should fix. This is purely because I [dispatch `getIssueFromUrl` before the navigation actually happens](https://github.com/gitpoint/git-point/blob/master/src/notifications/screens/notifications.screen.js#L194-L201).

The difference here between loading an issue straight from the repository _or_ issue list screens is that in the latter[ we already have the issue object and I navigate straight to it using it](https://github.com/gitpoint/git-point/blob/master/src/components/issue-list-item.component.js#L47-L49).

In the notifications screen we don't have the `issue` object so I first retrieve it and then navigate to the `issue` screen with it hence why there's a noticeable lag. What we can just do here is possibly pass a separate prop to identify a URL being passed instead of the issue object and in that scenario render both calls in the `IssueScreen` `compoonentDidMount`. That way the user gets navigated directly to the issue screen and the loading icon will show but with the difference that there's just an additional call that needs to be completed first.

If anybody wants to work on this, please don't hesitate to ask any questions <3

**Comment by Antondomashnev** [comment]
I would like to work on it.
