### ISSUE TITLE
User-profile bug

### ISSUE THREAD

**Issue by RogerAbyss** [gitpoint/git-point#152]
click "Followers" in "User" page, and choose a person to click in.
when i click left back button back to “User” page, i find ther is nothing.Page may should be refresh.
![984a99ab-0f39-4b24-bbb1-f37878dfe62a](https://user-images.githubusercontent.com/8122587/28498455-98bd416c-6fd0-11e7-983d-4d6d433173a2.png)

**Comment by housseindjirdeh** [comment]
Thanks for logging this! Unforuntately this isn't a user profile specific bug but something deeper with regards to navigation. Navigating backwards to the same screen will show an incorrect state because state isn't refreshed. Already have an issue open for that #3.

This isn't trivial and is unfortunately something I wish we could find a solution for 🤔
