### ISSUE TITLE
Status Bar text color on Repository and User Profile Screen

### ISSUE THREAD

**Issue by darecki** [gitpoint/git-point#176]
Status Bar text is black on a dark gray background. It's completely unreadable. We should either make it white or hide it completely if it's not relevant. The same issue is visible on the user profile page. 
![repository](https://user-images.githubusercontent.com/3084606/28668606-e617a364-72d0-11e7-95d1-982f02404120.png)

**Comment by darecki** [comment]
Unfortunately I found out that my implementation changes the status bar color for all the screens. The question is why is it happening that way?

**Comment by andrewda** [comment]
I think there was some discussion around this in #4.

**Comment by housseindjirdeh** [comment]
Thanks a million for logging this @darecki and getting some code up for it so fast :)

So I opened a similar issue for this exact thing #4 and the behaviour is weird unfortunately. Although adding the prop to`ViewContainer` should only change it for the current screen since it ties into the `StatusBar` API - it's how we defined navigation in the app that's causing this. The app works with a  [TabNavigator](https://github.com/gitpoint/git-point/blob/master/routes.js#L221) routing logic where each tab is a separate _stack_ of screens. `AuthProfile` happens to be the first screen in the last stack of the tab (see [here](https://github.com/gitpoint/git-point/blob/master/routes.js#L259-L271) and [here](https://github.com/gitpoint/git-point/blob/master/routes.js#L206-L219)). For some unusual reason - changing the status bar for the first screen in the stack changes it for all screens which is unfortunate.

@ShaunLloyd spent a little bit of time looking at this and there's discussion over at #4 so I'll close this duplicated issue. Happy to discuss the approach to your PR there and figure out how we can best solve this 🎉
