### ISSUE TITLE
Welcome screen change

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#181]
After the introduction of onboarding swiper in PR #174, the question arises, do you really need a welcome screen at all? After entering the application, you see this screen:

![image](https://user-images.githubusercontent.com/4408379/28743168-e044cb8e-744b-11e7-87d5-ee33f305eede.png)

But what's the point in it? I understand, so we welcome the user, I'm not against it, but maybe then let's make it automatically enter the application (e.g. in 5 seconds),  and not by pressing the enter button?
It's not very convenient, you have to press it every time after login, especially considering that except to enter, nothing more can be done.

I would also suggest somehow redesign of this screen, for example add an animation background or something like that, it would be cool! And we can change the text, eg "Welcome back to GitPoint!", if the user has previously been authorized with app (optional).

What thoughts?

**Comment by andrewda** [comment]
I think at one point we were going to show the privacy policy there, but that didn't get done.

**Comment by housseindjirdeh** [comment]
Yep I was considering having the privacy policy there but decided that wasn't the best place to put it and felt it belonged more in the auth `user settings` section list of their screen.

So I initially built this screen specifically because I wanted the user `LOGIN.SUCCESS` to fire and complete before they're navigate to the app. For some reason I was running into an issue trying to immediately navigate to the main part of the app after the authentication screen and decided to have an intermediate `welcome` screen so that they can only click `Enter` when the user authentication call is complete (that button appears only then).

Definitely still think screen is kind of unnecessary and if it's possible would rather have a loading spinner that just navigates the user automatically to the main part of the app when they're authenticated.

**Comment by lex111** [comment]
I would leave it, considering it as a user greeting, but with the user automatically navigates to the main application screen.

**Comment by housseindjirdeh** [comment]
I like that, leave a message at the center of the screen with a loading indicator underneath and the user is automatically navigated when the call is complete :+1: 

I'll get to this shortly :)
