### ISSUE TITLE
Commit message conventions

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#190]
Let's try? What are some thoughts on this subject?

Useful links to explore:
https://conventionalcommits.org/
https://github.com/kazupon/git-commit-message-convention
https://github.com/marionebl/commitlint

**Comment by andrewda** [comment]
All for it! My personal format is just in a sentence, present-tense, imperative-style. For example, I do `Change this feature` instead of `changed this feature`.

In bigger projects, though, I can definitely see the need for more detailed commits including change type. I really like https://github.com/marionebl/commitlint but I'm not a fan of the other one because of the enforced emojis in commit titles.

Along with this, we might also want to setup some versioning conventions. There are quite a few questions that arise around this. When should we release new patch/minor/major updates? Should we consider any change that would require an iOS update "major"? Should all these be immediately pushed to the device using CodePush, or should we exclude all major updates?

**Comment by lex111** [comment]
We need to discuss this, including versioning conventions. I suggest also to add a new label - `under discussions`.

**Comment by RolfKoenders** [comment]
Interesting points indeed. I'm all for a convention on commit messages. We should also consider a issue/pr template file.

**Comment by housseindjirdeh** [comment]
_Definitely_ for this.

Okay so I think we're all on board to have:

1. A commit convention. How can we enforce this? Or can we just include it into our contributing guidelines for newer contributors?
2. Versioning conventions is definitely something we need to consider. Again, we'll need to keep in mind CodePush can't take care of native code updates, so maybe we can revolve major updates around that?
3. Definitely down for issue/PR templates. I'm okay with not having an issue one but I think a PR template will be extremely useful.

If no one gets to it - I'll open issues for 2. and 3. and leave this as discussion for commit conventions.

**Comment by andrewda** [comment]
@housseindjirdeh I've contributed to repos with pre-commit hooks that enforce the commit style. I'd like to see how we could do that.

**Comment by housseindjirdeh** [comment]
@andrewda awesome :) I was just wondering if that could be done with ore commit hooks - definitely think it would be great to have!

**Comment by lex111** [comment]
So we follow the format of the commits messages, [as in Angular](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit), do I understand correctly? Although I'm not familiar with this, but let's try :+1:

**Comment by andrewda** [comment]
@lex111 it's the style Google uses on almost all their repos and it works pretty well!

**Comment by lex111** [comment]
Now we need to do releases and in fact we have `0 releases`.

**Comment by Antoine38660** [comment]
I'm working on the issue #5 and I already some commits without this style :innocent:
What's going to happen?

**Comment by andrewda** [comment]
Nothing will happen, probably (unless you need to do some big rebasing). Just use the style in your PR title and everything should work fine.
