### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by umarmughal** [gitpoint/git-point#222]
It supports GitLab or not yet?

**Comment by FlorianTaut** [comment]
@umarmughal at the moment not.

**Comment by andrewda** [comment]
I don't expect this app to work with GitLab (or BitBucked, etc.) simply because it would require _a ton_ of changes to the API and managing notifications and an events screen between both would be very challenging. This isn't a mobile git client, it's a mobile GitHub client.

That being said, I'm not sure where @housseindjirdeh stands on this. It would be doable to implement GitLab _eventually_, but I foresee a lot of ugly and confusing API code and a difficult UI/UX if we go that route.

**Comment by housseindjirdeh** [comment]
Thanks for asking @umarmughal :)
 
@andrewda I couldn't have said it better myself. I agree that it would be _amazing_ to have GitLab and BitBucket support in this app and the ability to switch between accounts but the amount of work required would be tremendous. It's something I thought of when I first built the app but it's not something I think we should think of doing anytime soon, especially since there's so much we plan on adding to app.

I'm okay with having an issue for this open (or closed - don't mind either way really) if anybody wants to discuss the potential of including such support in the future 💬

**Comment by machour** [comment]
Closing this to get a clearer issue list.
Don't hesitate to continue the conversation here though 😉
