### ISSUE TITLE
Navigate to AuthProfileScreen for the Current User

### ISSUE THREAD

**Issue by wlisrausr** [gitpoint/git-point#247]
**Current process**

- I could find my own profile via Search menu navigation (for Users) and try to follow myself via triple dots menu "..." (at top right corner of the screen).
![screen shot 2017-08-13 at 8 53 46 pm](https://user-images.githubusercontent.com/4316908/29250429-7fc02006-806c-11e7-914e-3436f172af73.png)

**Suggestion**

- How about we remove that menu if the profile that we searched for is our own profile?

What do you guys think? @housseindjirdeh @andrewda

**Comment by andrewda** [comment]
I think there's another issue for redirecting you to our AuthProfile if you're on your own user profile.

**Comment by wlisrausr** [comment]
Wait, I still don't get it. So, we just need to redirect to profile page if we click on our own user profile in the search list? Is that exactly what we need to do? @andrewda

**Comment by andrewda** [comment]
Any time the user clicks on their own profile from anywhere, it should send them to the `AuthUser` page (the page that shows up when you click the profile icon in the bottom right).

**Comment by housseindjirdeh** [comment]
Yep thanks for this @wlisrausr.
 
So there are two screens, `AuthProfileScreen` and `UserProfileScreen`. The `AuthProfileScreen` shows additional information and a settings cog na instead of the three dots. We just need to conditionally make sure anytime the user tries to navigate to their own profile it takes them to `AuthProfileScreen` and not the other one.

Can't seem to find the other issue @andrewda. If that doesn't exist, happy to have that functionality worked out as part of this ticket :)

**Comment by andrewda** [comment]
Ok @housseindjirdeh, thinking back now I think it was a comment on an issue or PR a while back.

**Comment by wlisrausr** [comment]
Ok. I'll work on it. Thanks a lot for your complete explanation @housseindjirdeh.

**Comment by lex111** [comment]
@wlisrausr I did similar in PR #211, but apparently missed the search results, you can see this PR and fix it.

**Comment by wlisrausr** [comment]
Great! That's exactly what I need. Thanks @lex111. I'll fix it

**Comment by andrewda** [comment]
Haha guess that's where I saw it @lex111 🙃

**Comment by housseindjirdeh** [comment]
So it's the `userListItem`component where we'll probably want to update this instead of specifically SearchScreen (right [here])https://github.com/gitpoint/git-point/blob/master/src/components/user-list-item.component.js#L114-L116) and [here](https://github.com/gitpoint/git-point/blob/master/src/components/user-list-item.component.js#L107-L109)). This is because screens like `FollowersListScreen` and `FollowingListScreen` can show yourself as a user where if clicked should also navigate to the authenticated user's profile.

I think it might be worthwhile to just make `UserListItem` stateful and mapped to the `state.auth.user` in order to conditionally navigate to `AuthProfile` or `Profile`. That way any screen that uses this component will navigate correctly.

**Comment by wlisrausr** [comment]
Yes, that's exactly what I thought. I'm working on it and thanks to make it more clearly @housseindjirdeh
