### ISSUE TITLE
Is the latest version 1.2?

### ISSUE THREAD

**Issue by chinesedfan** [gitpoint/git-point#299]
I saw GitPoint is version 1.2 in AppStore. But codes(i.e. package.json) are 1.1.

Is it a mistake or did I miss something?

**Comment by andrewda** [comment]
Good question. cc @housseindjirdeh

**Comment by housseindjirdeh** [comment]
That's a very good question, and this is due to the fact that iOS was first released before Android (hence is one build step ahead). You'll notice both Android and package.json reflect 1.1.

Will streamline this so the next release will show 1.3 on all platforms. Thanks for logging this @chinesedfan :)

**Comment by chinesedfan** [comment]
Thanks for reply! Do all platforms keep this same when >= 1.3?

**Comment by housseindjirdeh** [comment]
Yep that's the plan, on the next release will try and _jump_ the Android + package.json versions so they can all be 1.3
