### ISSUE TITLE
Hide readme button if no readme

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point#309]

**Comment by housseindjirdeh** [comment]
Agreed this should be relatively simple as well :+1:

**Comment by chinesedfan** [comment]
Because no existing field in `repository` object, we should move `getReadMeByDispatch` from `read-me.screen` to `repository.screen`.

- If blocking loading, `repository.screen` may become slower.
- If hiding readme button after the request is returned, users may find ui changed suddenly.

I prefer the second, how about you?

**Comment by machour** [comment]
@chinesedfan I prefer the second option too, but starting with a hidden README button. If there's a readme, we update the UI to show it (like we do for the "Merge" button).
