### ISSUE TITLE
[Suggestion] Add dark theme

### ISSUE THREAD

**Issue by Rex501st** [gitpoint/git-point#59]
This isn't an issue, but more of a wish lish. Dark themes are nice and alot easier on the eyes. Love the app!

**Comment by housseindjirdeh** [comment]
Thank you I'm glad you like the app so much :+1: 

This can be a cool addition but definitely not a very high priority in my opinion. If someone would like to get their hands building this out sooner rather than later however, that would be awesome nonetheless :)

Will love to come to a complete consensus before this feature is stared. Here's what I 'm thinking:

1. Leverage a HOC to accept `theme` as a prop OR use a theming library like `react-native-theme`
2. Switching themes can be done in the user profile screen in the same settings screen we'll eventually add as part of #8. Clicking a switch theme `ListItem` there can just open an Action Sheet (or we can have a list of radio buttons of available themes that the user can select maybe)

Will love to hear other people's thoughts on this!

**Comment by rancidfrog** [comment]
Dark theme and transparent theme would be great.
Twidere - https://github.com/TwidereProject/Twidere-Android
is a twitter client with transparent theme.
