### ISSUE TITLE
add precommit hook + enforce eslint rules

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point#66]
As mentioned, let's narrow down our eslint/formatting preferences in the codebase. We can use this thread for discussion.

I'm a huge fan of `prettier` - we can do a [`prettier-eslint`](https://gist.github.com/cadebward/c26e218220d653385d876f9a81308140) pre-commit hook? Thoughts? CC @alejandronanez @patw0929

**Comment by patw0929** [comment]
`prettier` is good.
I used [`lint-staged`](https://github.com/okonet/lint-staged) + [`prettier`](https://github.com/prettier/prettier) before.

And which eslint config base should we use? Or just custom rules?

**Comment by patw0929** [comment]
Just a test, I made a lint-staged + prettier branch:
https://github.com/patw0929/git-point/tree/feature/prettier-n-eslint

I added some eslint rules. Including the import lint, so I think that removing babel resolve module alias should be better. Although it's convenient, but sometimes it confuse me, "Is this import a packages or actual path?".

Btw, it might be large commits, because we need fix many lint warnings & errors after enabling eslint.

**Comment by alejandronanez** [comment]
@housseindjirdeh @patw0929 
+1 on travis, that's great.
About prettier I have never used but I want to, so, go for it, I remember on my last a project had it and prettier was enforcing something like:
`<Foo foo={1} bar={2} baz={3} />`
That's not so good for diffing/reading purposes, we should enforce:
```js
<Foo
    foo={1}
    bar={2}
    baz={3}
/>
```
that being said, go ahead with prettier =]

Is it possible to not format all files at once? Maybe it would be better to do it incrementally, let's say, I modify `path/to/foo.js` so I apply `prettier` to that particular file, it would be easier to track down changes. Thoughts?

**Comment by housseindjirdeh** [comment]
@alejandronanez so with a prettier plugin in your editor you should be able to format single files at a time

Thanks again @patw0929 for adding this to project 🙌
