### ISSUE TITLE
Annoying bugs when star project and enter some project

### ISSUE THREAD

**Issue by garywill** [gitpoint/git-point#853]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.6.0      |
| Devices tested?  | iPhone SE |

---

## What Currently Happens?
1. Everytime I star a project, API error happens. Staring is successful.
![file_1](https://user-images.githubusercontent.com/32130780/49058483-1ddee680-f1fc-11e8-9ade-9676772799ef.png)

1. When enter [this project](https://github.com/andrew-d/static-binaries), API error and blank screen.
![file_0](https://user-images.githubusercontent.com/32130780/49058514-33eca700-f1fc-11e8-986c-9cf37eda90a1.png)

These annoying bugs didn't exist on 1.5.0. Please fix them. If you can't fix them soon, could you please rollback to 1.5.0 on App Store?

**Comment by chinesedfan** [comment]
@garywill Sorry for the inconvenience.

1. I have prepared a branch [fix_853](https://github.com/gitpoint/git-point/tree/fix_853) trying to fix it.
2. It's due to Github's API inconsistence. Check https://github.community/t5/GitHub-API-Development-and/Keep-deleted-issue-author-as-ghost/m-p/15456. And if no feedbacks from Github, we will consider to be compatible with it.
